In [2]:
import torch
import torchaudio


In [13]:
voxceleb = torchaudio.datasets.VoxCeleb1Verification(r'/mnt/d/programming/datasets/VoxCeleb', download=True,meta_url="/mnt/d/programming/datasets/VoxCeleb/list_test_hard2.txt")

In [16]:
# transform= torchaudio.transforms.Resample(orig_freq=16000, new_freq=8000)
def collate_fn(batch):

    return batch

In [25]:
batch_size = 1
test_loader = torch.utils.data.DataLoader(voxceleb, batch_size,shuffle=True)

In [50]:
next(iter(test_loader))

[tensor([[[ 0.0904,  0.0674, -0.0121,  ...,  0.1079,  0.1278,  0.1056]]]),
 tensor([[[-0.0027, -0.0041, -0.0081,  ...,  0.0007,  0.0007,  0.0006]]]),
 tensor([16000]),
 tensor([0]),
 ('id10054-aBpmA6-g2uw-00005',),
 ('id10677-s1sqH8pCwas-00009',)]

In [8]:
#!python verification_wvlm.py --model_name wavlm_base_plus --wav1 trial_wavs/hn8GyCJIfLM_0000012.wav --wav2 trial_wavs/HXUqYaOwrxA_0000015.wav --checkpoint C:\Users\KHADGA JYOTH ALLI\Desktop\programming\Class Work\IITJ\Speech Understanding\Assignment 2\model_checkpoints\wavlm_base_plus_nofinetune.pth

In [55]:
wav1_dir=r"/mnt/c/Users/KHADGA JYOTH ALLI/Desktop/programming/Class Work/IITJ/Speech Understanding/Assignment 2/trial_wavs/hn8GyCJIfLM_0000012.wav"
wav2_dir=r"/mnt/c/Users/KHADGA JYOTH ALLI/Desktop/programming/Class Work/IITJ/Speech Understanding/Assignment 2/trial_wavs/xTOk1Jz-F_g_0000015.wav"
            
# wav1, wav2, label = batch
wav1, sr1 = torchaudio.load(wav1_dir)
wav2,sr2 = torchaudio.load(wav2_dir)
resample1 = torchaudio.transforms.Resample(orig_freq=int(sr1), new_freq=16000)
resample2 = torchaudio.transforms.Resample(orig_freq=int(sr2), new_freq=16000)
wav1 = resample1(wav1)
wav2 = resample2(wav2)

In [61]:
wav1.squeeze_(0).shape

torch.Size([1, 78721])

In [60]:
wav2.shape

torch.Size([1, 142721])